# Generated by Django 2.0.2 on 2018-04-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.CharField(max_length=20, verbose_name='요금제'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
