# Generated by Django 2.0.2 on 2018-04-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20180402_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='생성날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_approval',
            field=models.BooleanField(default=False, verbose_name='승인완료'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_deposit',
            field=models.BooleanField(default=False, verbose_name='입금완료'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_reserved',
            field=models.BooleanField(default=False, verbose_name='예약완료'),
        ),
    ]
