# Generated by Django 2.0.2 on 2018-03-24 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorized',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized', to='accounts.University'),
        ),
        migrations.AlterField(
            model_name='department',
            name='categorized',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.Categorized'),
        ),
        migrations.AlterField(
            model_name='mentor_univ',
            name='univ_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='univ_category', to='accounts.Department', verbose_name='학교/계열/학과'),
        ),
    ]
