# Generated by Django 2.0.2 on 2018-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180324_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor_univ',
            name='is_agreement',
            field=models.BooleanField(default=False, verbose_name='서비스이용약관'),
        ),
        migrations.AddField(
            model_name='mentor_univ',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='개인정보이용'),
        ),
        migrations.AlterField(
            model_name='mentor_univ',
            name='is_sms',
            field=models.BooleanField(default=False, verbose_name='SMS광고수신'),
        ),
    ]
