# Generated by Django 2.0.2 on 2018-03-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor_univ',
            name='is_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor_univ',
            name='vouchers',
            field=models.ImageField(blank=True, null=True, upload_to='profile/%Y/%m/%d', verbose_name='증빙자료첨부'),
        ),
    ]
